-- [IX] SEQUENCE : 순차번호 생성기, 대부분 인위적인 PK사용 용도

-- EX.FRIEND TABLE과 그 테이블을 위한 SEQUENCE 만들기 
-- 1) SEQUENCE
DROP SEQUENCE FRIEND_SEQ; -- DROP을 해봄으로써 기존에 같은이름의 테이블이 있는지 확인 

CREATE SEQUENCE FRIEND_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE
    NOCACHE;
    
-- 2) CREATE TABLE    
DROP TABLE FRIEND;

CREATE TABLE FRIEND(
    NUM           NUMBER(4)   PRIMARY KEY,
    NAME          VARCHAR2(30) NOT NULL,
    PHONE         VARCHAR2(20)  UNIQUE,  -- UNIQUE: 유일, NULL허용
    TEL           VARCHAR2(20),
    LAST_MODIFIED DATE       DEFAULT SYSDATE
);

-- 3) 데이터 추가
INSERT INTO FRIEND (NUM, NAME, PHONE)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999');
INSERT INTO FRIEND (NUM, NAME, PHONE, TEL)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '02-123-1234');
INSERT INTO FRIEND (NUM, NAME, PHONE, TEL)
    VALUES (FRIEND_SEQ.NEXTVAL, '신길동', '010-2323-2323','02-234-2323');
INSERT INTO FRIEND 
    VALUES (FRIEND_SEQ.NEXTVAL, '김길순', NULL, NULL, SYSDATE);

SELECT * FROM FRIEND;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 현재 시퀀스 값

-------- <연 습 문 제> ----------

-- * 동일한 이름의 테이블이 기존에 있는지 확인하고, CUSTOMUER, CUS_LEVEL TABLE 만들기
DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;

CREATE TABLE CUS_LEVEL(
    LEVELNO    NUMBER(5)    PRIMARY KEY,
    LEVELNAME  VARCHAR(10)  NOT NULL
);

--     CUTOMER TABLE의 CNO번호는 시퀀스를 생성한다
CREATE SEQUENCE CUS_SQ
    MAXVALUE 9999;
    
CREATE TABLE CUSTOMER(
    CNO         NUMBER(5)    PRIMARY KEY,
    CNAME       VARCHAR2(20)   NOT NULL,
    JOINDATE    DATE       DEFAULT SYSDATE,
    PHONE       VARCHAR(50)    UNIQUE,
    POINT       NUMBER(10),
    LEVELNO     NUMBER(5)   REFERENCES CUS_LEVEL(LEVELNO)
);

-- CUS_LEVEL TABLE에 데이터 추가하기
INSERT INTO CUS_LEVEL
    VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL
    VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL
    VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL
    VALUES (4, 'BLACK');
    
SELECT * FROM CUS_LEVEL;

-- CUSTOMER TABLE에 데이터 추가하기
INSERT INTO CUSTOMER
    VALUES(CUS_SQ.NEXTVAL, '홍길동', TO_DATE('20171017','YYYYMMDD'), '010-9999-9999', 300, 1);
INSERT INTO CUSTOMER
    VALUES(CUS_SQ.NEXTVAL, '이철수', TO_DATE('20161112','YYYYMMDD'), '010-8888-8888', NULL, 2);

SELECT * FROM CUSTOMER;
DESC CUSTOMER;

-- 추가된 CUSTOMER TABLE 데이터 내용 제시된 대로 변경하기
SELECT CNO, CNAME, TO_CHAR(JOINDATE,'YYYY-MM-DD') , PHONE, POINT, LEVELNAME
    FROM CUS_LEVEL L, CUSTOMER C
    WHERE L.LEVELNO = C.LEVELNO;
