DROP TABLE ORDER1;
DROP TABLE CUS_INFO;
DROP TABLE GOODS;
DROP TABLE POCKET;
DROP TABLE ORDER2;

-- 1) 회원정보
CREATE TABLE CUS_INFO(
    ID        VARCHAR2(50)     PRIMARY KEY,
    NAME      VARCHAR2(50),
    TEL       VARCHAR2(50)      NOT NULL,
    ADDRESS   VARCHAR2(250),
    EMAIL     VARCHAR2(250)
); 
SELECT * FROM CUS_INFO;

-- 2) 주문테이블1

CREATE SEQUENCE ORDER1_SEQ
    START WITH 1   
    INCREMENT BY 1  
    MAXVALUE 99999  
    MINVALUE  1
    NOCYCLE 
    NOCACHE;

CREATE TABLE ORDER1(
    BUYNO   NUMBER(20)  PRIMARY KEY,
    ID      VARCHAR2(50) REFERENCES   CUS_INFO(ID),
    ADDRESS VARCHAR2(250),
    TEL     VARCHAR2(50),
    ORDER_DATE VARCHAR2(50)
);
SELECT * FROM ORDER1;

-- 3) 상품정보 
CREATE TABLE GOODS(
    GOODSCODE       VARCHAR2(50) PRIMARY KEY,
    GOODSNAME       VARCHAR2(50),
    ONEGOODSPRISCE  NUMBER(10),  
    GOODSPCS        NUMBER(5)
);
SELECT * FROM GOODS;
    
-- 4) 장바구니 
CREATE SEQUENCE POC_SEQ
    START WITH 1   
    INCREMENT BY 1  
    MAXVALUE 9999999999 
    MINVALUE  1
    NOCYCLE 
    NOCACHE;

CREATE TABLE POCKET(
    SEQNO   NUMBER(20) PRIMARY KEY,
    ID      VARCHAR2(50) REFERENCES   CUS_INFO(ID),
    GOODSCODE VARCHAR2(50) REFERENCES  GOODS(GOODSCODE),
    BUYPCS  NUMBER(10),
    PRICE   NUMBER(10)
);
SELECT * FROM POCKET;


-- 5) ORDER2 
CREATE SEQUENCE ORDER2_SEQ
    START WITH 1   
    INCREMENT BY 1  
    MAXVALUE 9999999999 
    MINVALUE  1
    NOCYCLE 
    NOCACHE;
    
CREATE TABLE ORDER2(
    SEQ_NO  NUMBER(2) PRIMARY KEY,
    BUYNO   NUMBER(20) REFERENCES  ORDER1(BUYNO),
    GOODSCODE VARCHAR2(50) REFERENCES  GOODS(GOODSCODE),
    BUYPCS  NUMBER(10),
    PRICE   NUMBER(10)
);
SELECT * FROM ORDER2;
